name: Build and Test (Galactic)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: galactic
      - name: Build rm_auto_aim
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: auto_aim_bringup
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: galactic
          skip-tests: true
      - name: Test armor_detector
        run: |
          source /opt/ros/galactic/setup.sh
          cd ros_ws
          colcon test --packages-select armor_detector --event-handlers console_cohesion+ --return-code-on-test-failure
      - name: Test armor_processor
        run: |
          source /opt/ros/galactic/setup.sh
          cd ros_ws
          colcon test --packages-select armor_processor --event-handlers console_cohesion+ --return-code-on-test-failure
